### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ghost** [fracpete/graphviz-treevisualize-weka-package#1]
On windows 7, using Weka 3.7, on clicking the plugins>graphvis visualisation option in the explorer window, an empty window appears without the visualisation.

**Comment by fracpete** [comment]
Do you have graphviz installed and its executable available through the PATH environmental variable?

**Comment by ghost** [comment]
I have it installed, however, it is not on the PATH directly. If that is the problem, then I would suggest that there ought to be a configuration mechanism available so that it is not necessary to have it on the PATH- very few programs are on the PATH as a matter of course in Windows.

**Comment by fracpete** [comment]
Hmm... Did you read the README of the project? It tells you how to configure the plugin in such a case.

**Comment by ghost** [comment]
If you are referring to the setup of the .props file, yes, I do have the props file in my wekafiles folder and accurately pointed to the dot.exe file.

**Comment by fracpete** [comment]
Would have been good to mention that in your original post.
Anyway, when you launch Weka from a console, train a J48 classifier on a simple dataset, like iris, and then launch the plugin, do you get any error message output in the console?

**Comment by ghost** [comment]
Apologies.

Yes, I do get errors, chiefly at the top:

```
Failed to execute graphviz command: [dot, -o, C:\Users\padler1\AppData\Local\Temp\\gvtv157.png, -T, png, C:\Users\padler1\AppData\Local\Temp\\gvtv157.dot]
java.io.IOException: Cannot run program "dot": CreateProcess error=2, The system cannot find the file specified
```

I have checked the directory for the executable, and it is correct. It does not work with backslashes, forwardslashes or escaped backslashes.

**Comment by fracpete** [comment]
Looks like it doesn't pick up your .props file, since it still uses the default "dot" executable. Can you post the exact name (case-sensitive!) of your props file and the content?

**Comment by ghost** [comment]
```
GraphVizTreeVisualization.props

Executable=C:/Program Files (x86)/Graphviz2.38/bin/
```

**Comment by fracpete** [comment]
The executable needs to be part of the path:

```
Executable=C:/Program Files (x86)/Graphviz2.38/bin/dot.exe
```

I just noticed that the `README` stated that the `.props` file needs to be placed in `wekafiles`. The correct location is `wekafiles/props`. I updated the `README` accordingly.

**Comment by ghost** [comment]
Murgh- sorry copy/pasting fail- it is a part of the path. But I'll try placing it in the props folder to see what happens.

**Comment by ghost** [comment]
Great. That solved it. Thankyou very much indeed for your assistance.
