### ISSUE TITLE
GraphViz: Blank window in Weka

### ISSUE THREAD

**Issue by teodoroarb** [fracpete/graphviz-treevisualize-weka-package#2]
I already installed the GraphViz, but when I run the visualizer in Weka, nothing happens. It just show a blank window. I have already installed the prefuse visualization toolkit too and it worked perfectly. But i would like to run the GraphViz too, because it seems better to print.

What could I do to solve this problem?

Thank you

**Comment by fracpete** [comment]
What OS are you running? Depending on your OS, you may have to configure where to find the `dot` executable, as explained in the [README.md](https://github.com/fracpete/graphviz-treevisualize-weka-package/blob/master/README.md) of the project. Pretty much only Linux will work out of the box, as Windows doesn't have a predefined location for the executable.

**Comment by teodoroarb** [comment]
I'm using linux Ubuntu. I don't have the wekafiles\props\ directory in my Weka. So, it just to create the props diretory inside the Weka directory and create the GraphVizTreeVisualization.props file?

**Comment by fracpete** [comment]
How did you install this package? If you install the ZIP file as _unofficial_ package (_File/URL_ button in Weka's Package manager), then you automatically get the `$HOME/wekafiles/props` directory.

**Comment by teodoroarb** [comment]
Yes, I installed the ZIP file as unofficial package. 
Ok, now I found the $HOME/wekafiles/props directory. I have another doubt: Where is the dot file? What is this dot file?
I search for this file on my computer, but I just found .dotx files, that is from Microsoft Word.

**Comment by fracpete** [comment]
The `dot` executable is part of the graphviz. It converts a graph in dot notation and turns it into graphical output, e.g., PNG -- this is what the plugin then displays.
The `which dot` command should return `/usr/bin/dot` if you have graphviz installed on your machine. I presume you installed it with something like this on your Ubuntu: `sudo apt-get install graphviz`

**Comment by teodoroarb** [comment]
Ok, today I'm in another computer. So, I'm making a test with Windows7. I downloaded the zip version and pasted in c:/. After, I created the GraphVizTreeVisualization.props file and pasted inside the $HOME/wekafiles/props directory. But nothing happened. 
The content of the GraphVizTreeVisualization.props file: Executable=C:/graphviz/bin/dot.exe
Am I forgetting something else?

**Comment by fracpete** [comment]
Here are my steps:
- fired up virtual instance of Windows 7 (had Java already installed)
- installed Weka 3.8.0
- downloaded and installed GraphViz 2.38 from [Softpedia](http://www.softpedia.com/get/Others/Miscellaneous/Graphviz.shtml) (graphviz.org wasn't responding)
- downloaded the [2014.8.1](https://github.com/fracpete/graphviz-treevisualize-weka-package/releases/download/v2014.8.1/graphviz-treevisualize-2014.8.1.zip) release of the plugin
- started Weka, opened Package manager, installed the plugin
- closed Weka
- created `C:\Users\fracpete\wekafiles\props\GraphVizTreeVisualization.props` with the following content (copy/pasted the path from the Windows Explorer and turned backslashes into forward slashes)

```
Executable=C:/Program Files/Graphviz2.38/bin/dot.exe
```
- restarted Weka, loaded iris dataset, ran J48, displayed tree and the plugin displayed the tree properly

**Comment by teodoroarb** [comment]
Great! It worked on linux!

Thanks
