### ISSUE TITLE
Readme Releases link for 2018.5.13 is wrong

### ISSUE THREAD

**Issue by tomasjuran** [fracpete/graphviz-treevisualize-weka-package#4]
On the README.md file, under Releases section, the link to download version 2018.5.13 is 

https://github.com/fracpete/graphviz-treevisualize-weka-package/releases/download/v2018.5.13/graphviz-treevisualize-2017.5.13.zip

but should be

https://github.com/fracpete/graphviz-treevisualize-weka-package/releases/download/v2018.5.13/graphviz-treevisualize-2018.5.13.zip

**Comment by fracpete** [comment]
Fixed. Thanks for reporting!
