### ISSUE TITLE
Crashes Weka when exporting to pdf

### ISSUE THREAD

**Issue by ProfessorPeregrine** [fracpete/graphviz-treevisualize-weka-package#6]
The add-in works fine for me until I export the graph as a pdf. It does export it, but it locks up Weka and all its windows to where I need to end the process in the task manager.

Weka v3.9.6
graphviz-treevisualize v2018.5.13 for 3.9.1+
Windows 10 64 bit

Thank you for your work in putting this together - it has helped me immensely!

**Comment by fracpete** [comment]
I'm a Linux users, so I just tried a virtual machine with Windows 10 and it worked fine for me.
What version of GraphViz are you using? Mine was the (ancient) 2.38.

**Comment by ProfessorPeregrine** [comment]
It looks like it is graphviz 3.0.0.

**Comment by fracpete** [comment]
2.50.0 worked for me.

**Correction:** The `dot` executable was hanging after it produced the output.

**Comment by fracpete** [comment]
Release [2022.4.13](https://github.com/fracpete/graphviz-treevisualize-weka-package/releases/tag/v2022.4.13) fixes this problem for me under Windows and now works with GraphViz 3.0.0 as well.

**Comment by ProfessorPeregrine** [comment]
Works for me as well! Thanks for the very quick response! And for adding the SVG save option. That is why I was saving in pdf in the first place. :)
