### ISSUE TITLE
It Is not compatible 

### ISSUE THREAD

**Issue by dirtyv4lk** [fracpete/graphviz-treevisualize-weka-package#7]
On Windows 10, using Weka 3.8.6, it doesn't even load the package according to the console window, It says: 
[WekaPackageManager] Skipping package graphviz-treevisualize because it is not compatible with Weka 3.8.6

**Comment by fracpete** [comment]
Which one did you download? There are two downloads available of version 2022.4.13, one for 3.9.x and one for 3.8.x

**Comment by dirtyv4lk** [comment]
it was the 3.9x
i got it from this link https://github.com/fracpete/graphviz-treevisualize-weka-package/releases/download/v2022.4.13/graphviz-treevisualize-2022.4.13-3.9.x.zip

**Comment by fracpete** [comment]
If you download the one for 3.8.x (see [Releases](https://github.com/fracpete/graphviz-treevisualize-weka-package#releases)), it should work with your Weka 3.8.6 installation.
